apiVersion: v1
data:
  mapRoles:
    - groups:
      - system:boostrappers
      - system:nodes
      rolearn: arn:aws:iam::erkjggkjlkjl;gjepogjosejio[gidjgjiod
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers:
    - groupds:
      - expense-pod-reader
      userarn: arn:aws:iam::730335449147:user/harish
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07005T01:35:42Z"
  name: aws-auth
  namespace: kube-system
  uid: 2c588f09-e535-4e99-9045-5c7d2e727493 #don't delete this